version: "3.7"

services :
  db:
    image: postgres:14.2
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"

  server:
    image: server
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    container_name: server
    build: 
      context: ./server
      #dockerfile: ./Dockerfile
    ports: 
      - "8001:8000"
    volumes: 
      - "./server:/app"
    depends_on: 
      - db

  client:
    image: client
    container_name: client
    build: 
      context: ./client/
      #dockerfile: ./Dockerfile
    ports: 
      - "4201:80"