version: "3.7"

services :
  db:
    image: postgres
    container_name: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  server:
    image: server
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: server
    build: 
      context: ./server
      #dockerfile: ./Dockerfile
    ports: 
    - "8000:8000"

  client:
    image: client
    container_name: client
    build: 
      context: ./client/
      #dockerfile: ./Dockerfile
    ports: 
    - 4200:80