"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--@7o330@qqgv*iyktgheh^mafrre--t10rxp&6+y5guw1r+vzu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'corsheaders',
    'auth_app',
    "core"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

MONGO_CONTAINER_NAME=os.environ.get('MONGO_CONTAINER_NAME', 'mongo')
MONGO_DB_HOST=os.environ.get('MONGO_DB_HOST', "mongo")
MONGO_DB_PORT=os.environ.get('MONGO_DB_PORT', 27017)
MONGO_INITDB_DATABASE=os.environ.get('MONGO_INITDB_DATABASE', "mongo_db")
MONGO_INITDB_ROOT_USERNAME=os.environ.get('MONGO_INITDB_ROOT_USERNAME', "mongo")
MONGO_INITDB_ROOT_PASSWORD=os.environ.get('MONGO_INITDB_ROOT_PASSWORD', "mongo")
DATABASE_ROUTERS = ['core.utils.db_routers.NonRelRouter', ]

POSTGRES_DB = os.environ.get('POSTGRES_DB', "postgres")
POSTGRES_USER = os.environ.get('POSTGRES_USER', "postgres")
POSTGRES_PASSWORD = os.environ.get('POSTGRES_PASSWORD', "postgres")
POSTGRES_DB_HOST = os.environ.get('POSTGRES_DB_HOST', "db")
POSTGRES_DB_PORT = os.environ.get('POSTGRES_DB_PORT', 5432)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_DB_HOST,
        'PORT': POSTGRES_DB_PORT,
    },
    "nonrel": { 
        "ENGINE": "djongo",
        "NAME": MONGO_INITDB_DATABASE,
        "CLIENT": {
            "host": MONGO_DB_HOST,
            "port": int(MONGO_DB_PORT),
            "username": MONGO_INITDB_ROOT_USERNAME,
            "password": MONGO_INITDB_ROOT_PASSWORD,
        },
        'TEST': {
            'MIRROR': 'default',
        },
    }
}

CACHE_TTL = 60 * 15 # 15 minutes

REDIS_CONTAINER_NAME=os.environ.get('REDIS_CONTAINER_NAME', 'redis')
REDIS_USERNAME=os.environ.get('REDIS_USERNAME', "default")
REDIS_PASSWORD=os.environ.get('REDIS_PASSWORD', "redis")
REDIS_PORT=os.environ.get('REDIS_PORT', 6379)
REDIS_LOCATION=f'redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_CONTAINER_NAME}:{REDIS_PORT}/0'
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_LOCATION,
    }
} 


CELERY_BROKER_URL=os.environ.get('CELERY_BROKER_URL', "redis://redis:6379/0")
REDIS_CHANNEL_URL=os.environ.get('REDIS_CHANNEL_URL', "redis://redis:6379/1")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_IGNORE_RESULT = True
CELERYD_HIJACK_ROOT_LOGGER = False

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

AUTH_USER_MODEL = 'auth_app.User'

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SERIALIZERS': {
        'user_create': 'auth_app.serializers.UserCreateSerializer',
        'user': 'auth_app.serializers.UserCreateSerializer',
    #    'current_user': 'authentication.serializers.CreateUserSerializer'
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4201",
]